{% set name = "pycosat" %}
{% set version = "0.6.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/archive/{{ version }}.tar.gz
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - msinttypes  # [win and py2k]
    - python
    - pip

  run:
    - python

test:
  files:
    - qg3-08.cnf
    - uf20-098.cnf
    - sudoku.py

  imports:
    - pycosat

about:
  home: https://github.com/conda/pycosat
  license: MIT
  license_file:
    - LICENSE
    - COPYRIGHT
  summary: Bindings to picosat (a SAT solver)
  description: |
    PicoSAT is a popular SAT solver written by Armin Biere in pure C. This
    package provides efficient Python bindings to picosat on the C level, i.e.
    when importing pycosat, the picosat solver becomes part of the Python
    process itself.
  doc_url: https://pypi.python.org/pypi/pycosat
  doc_source_url: https://github.com/conda/pycosat/blob/master/README.rst
  dev_url: https://github.com/conda/pycosat

extra:
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - msarahan
    - pelson
    - nehaljwani
    - mingwandroid
